#!/bin/zsh

BRANCH="$1"
DIRECTION="$2"
FROM_BRANCH="$3"

WITH="$4"
MESSAGE="$5"

if [[ -n "$FROM_BRANCH" ]]; then
    gh pr create --title "${MESSAGE:-"Deploy release from $FROM_BRANCH"}" --body "" --head "$FROM_BRANCH" --base "$BRANCH"
fi
