#!/bin/zsh

WAIT=2

PREVIEW=0

while [[ "$1" =~ ^- && ! "$1" == "--" ]]; do case $1 in
  -h || --help )
    echo "gh-deploy [options] <branch that will be deployed> from <base branch> [with <message>]"
    echo -e "\nOPTIONS:"
    echo -e "\t-p/--preview:\tpreview git logs that will be deployed"
    exit
    ;;
  -p | --preview )
    PREVIEW=1
    ;;
esac; shift; done
if [[ "$1" == '--' ]]; then shift; fi

BRANCH="$1"
DIRECTION="$2"
FROM_BRANCH="$3"

WITH="$4"
MESSAGE="$5"

git log --pretty=format:'%Cred%h%Creset %Cgreen(%cD)%Creset %C(cyan)%cn%Creset%x09%s %C(yellow)%d%Creset' --abbrev-commit origin/$BRANCH..origin/$FROM_BRANCH

if [[ $PREVIEW -eq 1 ]]; then
    exit
fi


if [[ -n "$FROM_BRANCH" ]]; then
    gh pr create --title "${MESSAGE:-"Deploy $BRANCH $DIRECTION $FROM_BRANCH"}" --body "" --head "$FROM_BRANCH" --base "$BRANCH" --label "release"
    sleep $WAIT
    gh pr merge "$FROM_BRANCH" --merge --delete-branch=false
fi
